name: Spring Boot CI/CD Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Manual trigger option

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: ./mvnw clean install
      
    - name: Run Tests
      run: ./mvnw test
      
    - name: Package Application
      run: ./mvnw package
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: demo-app
        path: target/*.jar
        
  deploy:
    name: Deploy to Development
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: demo-app
          
      - name: Deploy to Development Server
        run: |
          echo "Deploying application to development server"
          # Add actual deployment commands here
          # Examples:
          # - SSH into server and deploy JAR
          # - Deploy to AWS Elastic Beanstalk
          # - Deploy to Azure App Service
          # For demo purposes, this is a placeholder
          echo "Application successfully deployed!"